### ISSUE TITLE
 recursive import

### ISSUE THREAD

**Issue by duoduo70** [Enalye/grimoire#11]
In main.gr
```grimoire
import "a.gr";
event start() {
    print(a);
}
```

In a.gr
```grimoire
import "b.gr"
export var a = b;
```

In b.gr
```grimoire
export var b = "test";
```

Compiler it.
```
Error:
error: `b` is not declared
  -> /<path>/a.gr(2,16)
  |
 2| export var a = b;
  |                ^  unknown variable
```

**Comment by Enalye** [comment]
Hi,

This one is also a tricky problem,
Global variables are parsed sequentially in the same order as the import order, which means that `b` is declared after `a` and that `a` as no way to know that `b` exists.

One easy solution would be to invert the parsing order to better match the dependency tree and it would certainly work for a simple example such as this one, but not help much if `b.gr` were to import `a.gr` as well, or import another file that do the same thing. Any circular dependency would have the same problem.

And forward declaration is only half of the issue here, what if we were in this situation?
> a.gr
```js
import "b.gr"
export var a = b;
```
> b.gr
```js
import "a.gr"
export var b = a;
```
How should the compiler behave ? Even if we were to forward reference both variable so they know that each other exists, the compiler has no way to infer the type of `a` or `b` because each depends on the type of the other.

Worse, both expect a value, but none can be initialized, which is illegal in grimoire (there are optional types for that).

Global variables are a flawed concept at core because they behave sequentially in the non-sequential environment of imported files.
Right now, I don’t have the solution to resolve this problem.
The only best practice I can advice is to avoid initializing a global variable with another one from another file (excepted variables from a GrLibrary).

**Comment by duoduo70** [comment]
Thank you very much!
